# Generated by Django 4.1.6 on 2023-02-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centra_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iap',
            name='IAP_model',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='iap',
            name='IAP_status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='iap',
            name='ip_address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='iap',
            name='is_virtual',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='iap',
            name='mac_address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='purchase_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In-Transit', 'In-Transit'), ('Delivered', 'Delivered')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='site',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='site',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='site',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='site',
            name='zipcode',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='switch',
            name='ip_address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='switch',
            name='mac_address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='switch',
            name='switch_model',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='switch',
            name='switch_status',
            field=models.CharField(default='', max_length=20),
        ),
    ]
