# Generated by Django 4.1.6 on 2023-02-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centra_inventory', '0002_alter_iap_iap_model_alter_iap_iap_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
